import type { DashboardData, PeriodKey } from "../_types/dashboard";

const periods: PeriodKey[] = ["7G", "30G", "90G", "YTD"];

export const mockDashboardData: DashboardData = {
  topbar: {
    title: "Gelir Paneli",
    subtitle: "son guncelleme: bugun 09:14",
    periods,
    defaultPeriod: "30G",
    aiStatusLabel: "AI Aktif",
  },
  sidebar: {
    logoPrimary: "revenic",
    logoAccent: ".ai",
    logoSub: "Revenue Engine",
    sections: [
      {
        id: "overview",
        label: "Genel Bakis",
        items: [
          { id: "dashboard", label: "Dashboard", href: "/dashboard", active: true },
          { id: "appointments", label: "Randevular", href: "/" },
          { id: "patients", label: "Hastalar", href: "/hasta" },
        ],
      },
      {
        id: "revenue",
        label: "Gelir",
        items: [
          { id: "ltv", label: "LTV Analizi", href: "/dashboard?section=ltv" },
          { id: "upsell", label: "Upsell / Cross-sell", href: "/dashboard?section=upsell" },
          { id: "bundles", label: "Bundle Satislar", href: "/dashboard?section=bundles" },
        ],
      },
      {
        id: "ai-tools",
        label: "AI Araclari",
        items: [
          { id: "forecasts", label: "AI Tahminler", href: "/dashboard?section=forecasts" },
          { id: "import", label: "Veri Ice Aktar", href: "/dashboard?section=import" },
        ],
      },
    ],
    clinicName: "Dental Studio",
    clinicPlan: "MVP - Pilot",
    clinicInitials: "DS",
  },
  insight: {
    title: "AI Insight",
    message:
      "7 yuksek-LTV hastaniz 90+ gun randevusuz. Hatirlatma gonderilirse tahmini ek gelir: ₺24.800. Ortalama tedavi kabul orani bu segmentte %71.",
    highlights: [
      "Bu ay 3 upsell firsati otomatik tespit edildi",
      "No-show riski gecen aya gore %18 azaldi",
    ],
    actionLabel: "Hatirlatma Gonder",
  },
  chairOccupancy: {
    badge: "Bugun - %78",
    cells: [
      "filled","filled","filled","filled","upsell","filled","filled","noshow",
      "filled","filled","upsell","filled","empty","filled","noshow","filled",
      "filled","upsell","filled","filled","noshow","filled","filled","filled",
      "empty","filled","filled","empty","filled","filled","filled","empty",
    ],
    legend: [
      { id: "filled", label: "Dolu", color: "rgba(124,92,252,0.6)" },
      { id: "upsell", label: "Upsell", color: "rgba(34,197,94,0.35)" },
      { id: "noshow", label: "No-show", color: "rgba(239,68,68,0.35)" },
      { id: "empty", label: "Bos", color: "var(--surface2)" },
    ],
    summary: [
      { id: "total", label: "Toplam Koltuk", value: "32" },
      { id: "filled", label: "Dolu", value: "25", valueColor: "var(--accent2)" },
      { id: "noshow", label: "No-show", value: "3", valueColor: "var(--red)" },
      { id: "empty", label: "Bos", value: "4", valueColor: "var(--muted)" },
    ],
  },
  opportunities: {
    potentialBadge: "₺67.200 potansiyel",
    items: [
      {
        id: "implant",
        icon: "🦷",
        iconBg: "var(--purple-dim)",
        title: "Implant Upsell Firsati",
        subtitle: "4 hasta - mevcut tedavi: kopru",
        estimatedAmount: "₺32.000",
      },
      {
        id: "whitening",
        icon: "✨",
        iconBg: "var(--green-dim)",
        title: "Beyazlatma Bundle",
        subtitle: "11 hasta - son 6 ay temizlik",
        estimatedAmount: "₺18.700",
      },
      {
        id: "ortho",
        icon: "📋",
        iconBg: "var(--amber-dim)",
        title: "Ortodonti Degerlendirme",
        subtitle: "7 hasta - risk skoru yuksek",
        estimatedAmount: "₺16.500",
      },
    ],
    alertText: "3 hasta 90+ gun inaktif - yuksek churn riski",
  },
  patientTable: {
    badge: "AI Skorlu",
    columns: ["Hasta", "LTV", "AOV", "AI Durum", "Firsat"],
    rows: [
      {
        id: "p1",
        name: "Ayse K.",
        meta: "12 ziyaret - 3 yil",
        ltv: "₺38.200",
        ltvTierColor: "var(--green)",
        aov: "₺3.180",
        status: "Aktif",
        statusTone: "confirmed",
        opportunity: "Implant",
        opportunityTone: "opportunity",
      },
      {
        id: "p2",
        name: "Mehmet D.",
        meta: "8 ziyaret - 2 yil",
        ltv: "₺29.400",
        ltvTierColor: "var(--green)",
        aov: "₺3.670",
        status: "Aktif",
        statusTone: "confirmed",
        opportunity: "Bundle",
        opportunityTone: "opportunity",
      },
      {
        id: "p3",
        name: "Zeynep A.",
        meta: "6 ziyaret - 18 ay",
        ltv: "₺18.900",
        ltvTierColor: "var(--amber)",
        aov: "₺3.150",
        status: "92 gun",
        statusTone: "pending",
        opportunity: "Hatirlat",
        opportunityTone: "opportunity",
      },
      {
        id: "p4",
        name: "Ali S.",
        meta: "4 ziyaret - 1 yil",
        ltv: "₺14.200",
        ltvTierColor: "var(--amber)",
        aov: "₺3.550",
        status: "No-show",
        statusTone: "risk",
        opportunity: "Upsell",
        opportunityTone: "opportunity",
      },
      {
        id: "p5",
        name: "Selin Y.",
        meta: "3 ziyaret - 8 ay",
        ltv: "₺8.100",
        ltvTierColor: "var(--red)",
        aov: "₺2.700",
        status: "Churn riski",
        statusTone: "risk",
        opportunity: "Degerlendir",
        opportunityTone: "pending",
      },
    ],
  },
  periodSnapshots: {
    "7G": {
      kpis: [
        { id: "ltv", label: "Ortalama Hasta LTV", value: "₺17.980", delta: "+%3.2 vs onceki 7G", deltaDirection: "up", subtext: "Aktif hasta basi - hedef ₺22k", dotColor: "var(--accent2)", isHero: true, heroTrendPoints: "0,38 14,36 28,34 42,30 56,24 70,20 84,16 100,12" },
        { id: "aov", label: "Ortalama Siparis Degeri (AOV)", value: "₺3.080", delta: "+%2.1", deltaDirection: "up", subtext: "ziyaret basi", dotColor: "var(--teal)" },
        { id: "cross-sell", label: "Cross-sell Geliri", value: "₺9.600", delta: "+%5.4", deltaDirection: "up", subtext: "7 gunde - 9 islem", dotColor: "var(--green)" },
        { id: "upsell", label: "Upsell Geliri", value: "₺7.450", delta: "+%4.0", deltaDirection: "up", subtext: "7 gunde - 6 islem", dotColor: "var(--amber)" },
        { id: "bundle", label: "Bundle Satis", value: "₺4.900", delta: "+%9.8", deltaDirection: "up", subtext: "7 gunde - 3 paket", dotColor: "#f472b6" },
        { id: "reminder", label: "AI Hatirlatma Geliri", value: "₺2.300", delta: "+%11.0", deltaDirection: "up", subtext: "geri donen hasta", dotColor: "var(--muted)" },
      ],
      revenueTrend: {
        labels: ["G1", "G2", "G3", "G4", "G5", "G6", "G7"],
        yoyBadge: "+%6.2 WoW",
        series: [
          { id: "base", label: "Temel Tedavi", color: "rgba(37,99,235,0.55)", values: [8, 9, 8, 10, 11, 9, 12] },
          { id: "cross", label: "Cross-sell", color: "rgba(22,163,74,0.5)", values: [2, 2, 3, 2, 3, 2, 3] },
          { id: "upsell-bundle", label: "Upsell + Bundle", color: "rgba(180,83,9,0.45)", values: [1, 2, 1, 2, 2, 2, 2] },
        ],
      },
      revenueFunnel: {
        badge: "Son 7 Gun",
        items: [
          { id: "base", label: "Temel Tedavi", ratioPct: 100, amount: "₺27.500", color: "rgba(124,92,252,0.6)" },
          { id: "cross", label: "Cross-sell", ratioPct: 35, amount: "₺9.600", color: "rgba(34,197,94,0.6)" },
          { id: "upsell", label: "Upsell", ratioPct: 27, amount: "₺7.450", color: "rgba(245,158,11,0.6)" },
          { id: "bundle", label: "Bundle", ratioPct: 18, amount: "₺4.900", color: "rgba(244,114,182,0.6)" },
          { id: "reminder", label: "Hatirlatma", ratioPct: 8, amount: "₺2.300", color: "rgba(20,184,166,0.6)" },
        ],
        totalLabel: "Toplam",
        totalAmount: "₺51.750",
      },
      noShow: {
        badge: "Haftalik",
        noShowRate: "%8.6",
        noShowDelta: "gecen hafta %9.8",
        lostRevenue: "₺2.240",
        lostRevenueDelta: "₺540 azaldi",
        dayLabel: "Gun bazli no-show",
        days: [
          { id: "mon", day: "Pzt", count: 2, barPct: 28 },
          { id: "tue", day: "Sal", count: 1, barPct: 14 },
          { id: "wed", day: "Car", count: 3, barPct: 42 },
          { id: "thu", day: "Per", count: 0, barPct: 4 },
          { id: "fri", day: "Cum", count: 2, barPct: 28 },
        ],
        aiForecast: "AI TAHMIN: Carsamba no-show riski hala yuksek. 24s oncesi hatirlatma oneriliyor.",
      },
      treatmentAcceptance: {
        badge: "%66 kabul",
        acceptedPct: 66,
        pendingPct: 20,
        rejectedPct: 14,
        legend: [
          { id: "accepted", label: "Kabul edildi", pct: 66, color: "var(--accent)" },
          { id: "pending", label: "Beklemede", pct: 20, color: "var(--amber)" },
          { id: "rejected", label: "Reddedildi", pct: 14, color: "var(--red)" },
        ],
        miniStats: [
          { id: "high-ltv", label: "Yuksek-LTV Kabul", value: "%79", valueColor: "var(--green)" },
          { id: "low-ltv", label: "Dusuk-LTV Kabul", value: "%49", valueColor: "var(--amber)" },
        ],
      },
    },
    "30G": {
      kpis: [
        { id: "ltv", label: "Ortalama Hasta LTV", value: "₺18.420", delta: "+%12.4 vs gecen ay", deltaDirection: "up", subtext: "Aktif hasta basi - hedef ₺22k", dotColor: "var(--accent2)", isHero: true, heroTrendPoints: "0,38 14,32 28,35 42,28 56,22 70,18 84,14 100,8" },
        { id: "aov", label: "Ortalama Siparis Degeri (AOV)", value: "₺3.240", delta: "+%8.1", deltaDirection: "up", subtext: "ziyaret basi", dotColor: "var(--teal)" },
        { id: "cross-sell", label: "Cross-sell Geliri", value: "₺41.600", delta: "+%23.7", deltaDirection: "up", subtext: "bu ay - 38 islem", dotColor: "var(--green)" },
        { id: "upsell", label: "Upsell Geliri", value: "₺28.950", delta: "+%15.2", deltaDirection: "up", subtext: "bu ay - 24 islem", dotColor: "var(--amber)" },
        { id: "bundle", label: "Bundle Satis", value: "₺19.400", delta: "+%31.0", deltaDirection: "up", subtext: "bu ay - 12 paket", dotColor: "#f472b6" },
        { id: "reminder", label: "AI Hatirlatma Geliri", value: "₺11.200", delta: "+%44.8", deltaDirection: "up", subtext: "geri donen hasta", dotColor: "var(--muted)" },
      ],
      revenueTrend: {
        labels: ["Oca", "Sub", "Mar", "Nis", "May", "Haz", "Tem", "Agu", "Eyl", "Eki"],
        yoyBadge: "+%18.3 YoY",
        series: [
          { id: "base", label: "Temel Tedavi", color: "rgba(37,99,235,0.55)", values: [62, 68, 72, 69, 78, 82, 88, 91, 94, 98] },
          { id: "cross", label: "Cross-sell", color: "rgba(22,163,74,0.5)", values: [18, 22, 24, 26, 28, 31, 35, 37, 39, 42] },
          { id: "upsell-bundle", label: "Upsell + Bundle", color: "rgba(180,83,9,0.45)", values: [8, 11, 14, 16, 18, 22, 26, 28, 30, 35] },
        ],
      },
      revenueFunnel: {
        badge: "Bu Ay",
        items: [
          { id: "base", label: "Temel Tedavi", ratioPct: 100, amount: "₺98.400", color: "rgba(124,92,252,0.6)" },
          { id: "cross", label: "Cross-sell", ratioPct: 42, amount: "₺41.600", color: "rgba(34,197,94,0.6)" },
          { id: "upsell", label: "Upsell", ratioPct: 29, amount: "₺28.950", color: "rgba(245,158,11,0.6)" },
          { id: "bundle", label: "Bundle", ratioPct: 20, amount: "₺19.400", color: "rgba(244,114,182,0.6)" },
          { id: "reminder", label: "Hatirlatma", ratioPct: 11, amount: "₺11.200", color: "rgba(20,184,166,0.6)" },
        ],
        totalLabel: "Toplam",
        totalAmount: "₺199.550",
      },
      noShow: {
        badge: "Haftalik",
        noShowRate: "%9.2",
        noShowDelta: "gecen ay %13.1",
        lostRevenue: "₺8.640",
        lostRevenueDelta: "₺3.200 azaldi",
        dayLabel: "Gun bazli no-show",
        days: [
          { id: "mon", day: "Pzt", count: 3, barPct: 30 },
          { id: "tue", day: "Sal", count: 2, barPct: 20 },
          { id: "wed", day: "Car", count: 5, barPct: 50 },
          { id: "thu", day: "Per", count: 1, barPct: 10 },
          { id: "fri", day: "Cum", count: 4, barPct: 40 },
        ],
        aiForecast: "AI TAHMIN: Carsamba no-show orani yuksek. 24s oncesi SMS aktive edilmesi oneriliyor.",
      },
      treatmentAcceptance: {
        badge: "%68 kabul",
        acceptedPct: 68,
        pendingPct: 18,
        rejectedPct: 14,
        legend: [
          { id: "accepted", label: "Kabul edildi", pct: 68, color: "var(--accent)" },
          { id: "pending", label: "Beklemede", pct: 18, color: "var(--amber)" },
          { id: "rejected", label: "Reddedildi", pct: 14, color: "var(--red)" },
        ],
        miniStats: [
          { id: "high-ltv", label: "Yuksek-LTV Kabul", value: "%81", valueColor: "var(--green)" },
          { id: "low-ltv", label: "Dusuk-LTV Kabul", value: "%52", valueColor: "var(--amber)" },
        ],
      },
    },
    "90G": {
      kpis: [
        { id: "ltv", label: "Ortalama Hasta LTV", value: "₺19.260", delta: "+%16.1 vs onceki 90G", deltaDirection: "up", subtext: "Aktif hasta basi - hedef ₺22k", dotColor: "var(--accent2)", isHero: true, heroTrendPoints: "0,42 14,38 28,34 42,30 56,24 70,18 84,12 100,6" },
        { id: "aov", label: "Ortalama Siparis Degeri (AOV)", value: "₺3.360", delta: "+%9.4", deltaDirection: "up", subtext: "ziyaret basi", dotColor: "var(--teal)" },
        { id: "cross-sell", label: "Cross-sell Geliri", value: "₺121.200", delta: "+%27.2", deltaDirection: "up", subtext: "90 gunde - 104 islem", dotColor: "var(--green)" },
        { id: "upsell", label: "Upsell Geliri", value: "₺83.400", delta: "+%19.9", deltaDirection: "up", subtext: "90 gunde - 73 islem", dotColor: "var(--amber)" },
        { id: "bundle", label: "Bundle Satis", value: "₺56.800", delta: "+%33.7", deltaDirection: "up", subtext: "90 gunde - 39 paket", dotColor: "#f472b6" },
        { id: "reminder", label: "AI Hatirlatma Geliri", value: "₺34.100", delta: "+%51.3", deltaDirection: "up", subtext: "geri donen hasta", dotColor: "var(--muted)" },
      ],
      revenueTrend: {
        labels: ["M1", "M2", "M3", "M4", "M5", "M6"],
        yoyBadge: "+%22.8 QoQ",
        series: [
          { id: "base", label: "Temel Tedavi", color: "rgba(37,99,235,0.55)", values: [120, 126, 134, 140, 148, 155] },
          { id: "cross", label: "Cross-sell", color: "rgba(22,163,74,0.5)", values: [40, 43, 48, 53, 57, 61] },
          { id: "upsell-bundle", label: "Upsell + Bundle", color: "rgba(180,83,9,0.45)", values: [22, 25, 31, 34, 38, 41] },
        ],
      },
      revenueFunnel: {
        badge: "Son 90 Gun",
        items: [
          { id: "base", label: "Temel Tedavi", ratioPct: 100, amount: "₺295.000", color: "rgba(124,92,252,0.6)" },
          { id: "cross", label: "Cross-sell", ratioPct: 41, amount: "₺121.200", color: "rgba(34,197,94,0.6)" },
          { id: "upsell", label: "Upsell", ratioPct: 28, amount: "₺83.400", color: "rgba(245,158,11,0.6)" },
          { id: "bundle", label: "Bundle", ratioPct: 19, amount: "₺56.800", color: "rgba(244,114,182,0.6)" },
          { id: "reminder", label: "Hatirlatma", ratioPct: 12, amount: "₺34.100", color: "rgba(20,184,166,0.6)" },
        ],
        totalLabel: "Toplam",
        totalAmount: "₺590.500",
      },
      noShow: {
        badge: "Ortalama 90G",
        noShowRate: "%8.4",
        noShowDelta: "onceki donem %10.9",
        lostRevenue: "₺24.800",
        lostRevenueDelta: "₺8.700 azaldi",
        dayLabel: "Gun bazli no-show",
        days: [
          { id: "mon", day: "Pzt", count: 8, barPct: 32 },
          { id: "tue", day: "Sal", count: 6, barPct: 24 },
          { id: "wed", day: "Car", count: 11, barPct: 44 },
          { id: "thu", day: "Per", count: 5, barPct: 20 },
          { id: "fri", day: "Cum", count: 9, barPct: 36 },
        ],
        aiForecast: "AI TAHMIN: Persembe gunu otomatik hatirlatma acildiginda iptal orani daha da dusecek.",
      },
      treatmentAcceptance: {
        badge: "%71 kabul",
        acceptedPct: 71,
        pendingPct: 17,
        rejectedPct: 12,
        legend: [
          { id: "accepted", label: "Kabul edildi", pct: 71, color: "var(--accent)" },
          { id: "pending", label: "Beklemede", pct: 17, color: "var(--amber)" },
          { id: "rejected", label: "Reddedildi", pct: 12, color: "var(--red)" },
        ],
        miniStats: [
          { id: "high-ltv", label: "Yuksek-LTV Kabul", value: "%84", valueColor: "var(--green)" },
          { id: "low-ltv", label: "Dusuk-LTV Kabul", value: "%57", valueColor: "var(--amber)" },
        ],
      },
    },
    YTD: {
      kpis: [
        { id: "ltv", label: "Ortalama Hasta LTV", value: "₺20.040", delta: "+%21.3 vs gecen yil", deltaDirection: "up", subtext: "Aktif hasta basi - hedef ₺22k", dotColor: "var(--accent2)", isHero: true, heroTrendPoints: "0,46 14,42 28,36 42,28 56,22 70,14 84,8 100,4" },
        { id: "aov", label: "Ortalama Siparis Degeri (AOV)", value: "₺3.480", delta: "+%12.2", deltaDirection: "up", subtext: "ziyaret basi", dotColor: "var(--teal)" },
        { id: "cross-sell", label: "Cross-sell Geliri", value: "₺356.000", delta: "+%29.6", deltaDirection: "up", subtext: "YTD - 298 islem", dotColor: "var(--green)" },
        { id: "upsell", label: "Upsell Geliri", value: "₺251.300", delta: "+%24.8", deltaDirection: "up", subtext: "YTD - 212 islem", dotColor: "var(--amber)" },
        { id: "bundle", label: "Bundle Satis", value: "₺168.900", delta: "+%39.4", deltaDirection: "up", subtext: "YTD - 121 paket", dotColor: "#f472b6" },
        { id: "reminder", label: "AI Hatirlatma Geliri", value: "₺102.500", delta: "+%58.2", deltaDirection: "up", subtext: "geri donen hasta", dotColor: "var(--muted)" },
      ],
      revenueTrend: {
        labels: ["Oca", "Sub", "Mar", "Nis", "May", "Haz", "Tem", "Agu", "Eyl", "Eki", "Kas", "Ara"],
        yoyBadge: "+%24.1 YTD",
        series: [
          { id: "base", label: "Temel Tedavi", color: "rgba(37,99,235,0.55)", values: [90, 98, 106, 112, 121, 129, 137, 145, 152, 159, 168, 176] },
          { id: "cross", label: "Cross-sell", color: "rgba(22,163,74,0.5)", values: [24, 28, 31, 35, 39, 43, 46, 50, 54, 58, 62, 66] },
          { id: "upsell-bundle", label: "Upsell + Bundle", color: "rgba(180,83,9,0.45)", values: [12, 15, 18, 22, 25, 29, 32, 35, 39, 42, 46, 49] },
        ],
      },
      revenueFunnel: {
        badge: "YTD",
        items: [
          { id: "base", label: "Temel Tedavi", ratioPct: 100, amount: "₺842.000", color: "rgba(124,92,252,0.6)" },
          { id: "cross", label: "Cross-sell", ratioPct: 42, amount: "₺356.000", color: "rgba(34,197,94,0.6)" },
          { id: "upsell", label: "Upsell", ratioPct: 30, amount: "₺251.300", color: "rgba(245,158,11,0.6)" },
          { id: "bundle", label: "Bundle", ratioPct: 20, amount: "₺168.900", color: "rgba(244,114,182,0.6)" },
          { id: "reminder", label: "Hatirlatma", ratioPct: 12, amount: "₺102.500", color: "rgba(20,184,166,0.6)" },
        ],
        totalLabel: "Toplam",
        totalAmount: "₺1.720.700",
      },
      noShow: {
        badge: "YTD Ortalama",
        noShowRate: "%7.9",
        noShowDelta: "gecen yil %11.4",
        lostRevenue: "₺79.300",
        lostRevenueDelta: "₺25.600 azaldi",
        dayLabel: "Gun bazli no-show",
        days: [
          { id: "mon", day: "Pzt", count: 20, barPct: 33 },
          { id: "tue", day: "Sal", count: 17, barPct: 28 },
          { id: "wed", day: "Car", count: 26, barPct: 43 },
          { id: "thu", day: "Per", count: 14, barPct: 23 },
          { id: "fri", day: "Cum", count: 22, barPct: 36 },
        ],
        aiForecast: "AI TAHMIN: Yil sonuna kadar no-show oranini %7.2 seviyesine cekmek mumkun.",
      },
      treatmentAcceptance: {
        badge: "%73 kabul",
        acceptedPct: 73,
        pendingPct: 16,
        rejectedPct: 11,
        legend: [
          { id: "accepted", label: "Kabul edildi", pct: 73, color: "var(--accent)" },
          { id: "pending", label: "Beklemede", pct: 16, color: "var(--amber)" },
          { id: "rejected", label: "Reddedildi", pct: 11, color: "var(--red)" },
        ],
        miniStats: [
          { id: "high-ltv", label: "Yuksek-LTV Kabul", value: "%86", valueColor: "var(--green)" },
          { id: "low-ltv", label: "Dusuk-LTV Kabul", value: "%59", valueColor: "var(--amber)" },
        ],
      },
    },
  },
};
